import type { Metadata } from "next"
import { Sofia_Sans } from "next/font/google"
import "./globals.css"
import Layout from "@/components/chat/Providers"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { MainNav } from "@/components/landing/Banner"
const lato = Sofia_Sans({
    subsets: ["greek"],
    weight: ["100", "300", "400", "700", "900"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
    locale,
}: {
    children: React.ReactNode
    locale: never
}) {
    return (
        <html lang={locale}>
            <body
                className={`${lato.className} bg-gradient-to-l from-gray-200 via-indigo-300 to-stone-100`}
            >
                <Analytics />
                <SpeedInsights />
                <Layout>
                    <MainNav />
                    {children}
                </Layout>
            </body>
        </html>
    )
}
