import type { Metadata } from "next"
import { Sofia_Sans } from "next/font/google"
import "./globals.css"
import Layout from "@/components/chat/Providers"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
const lato = Sofia_Sans({
    subsets: ["greek"],
    weight: ["100", "300", "400", "700", "900"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="es">
            <Analytics />
            <SpeedInsights />
            <Layout>
                <body className={`${lato.className} bg-white`}>{children}</body>
            </Layout>
        </html>
    )
}
